import featuredBitcoin from "@/assets/featured-bitcoin.jpg";
import marketAi from "@/assets/market-ai.jpg";
import marketCricket from "@/assets/market-cricket.jpg";
import type { Market } from "./types";

export const markets: Market[] = [
  {
    id: "btc-120k-december",
    title: "Will Bitcoin reach $120,000 before December?",
    category: "Crypto",
    closesAt: "2d 8h",
    volume: "2.4M TAC",
    participants: 12482,
    outcomes: [
      { id: "yes", label: "Yes", probability: 64 },
      { id: "no", label: "No", probability: 36 },
    ],
    image: featuredBitcoin,
    featured: true,
    trend: "up",
    description: "This market tracks whether Bitcoin trades at or above $120,000 on a major USD spot exchange before the closing time.",
    source: "CoinGecko",
    sourceUrl: "https://www.coingecko.com/en/coins/bitcoin",
    resolutionCriteria: "Resolves Yes if the reported Bitcoin USD spot price reaches $120,000 before market close; otherwise No.",
  },
  {
    id: "ai-product-2026",
    title: "Will a major AI lab release a consumer robot in 2026?",
    category: "Technology",
    closesAt: "18d",
    volume: "842K TAC",
    participants: 6381,
    outcomes: [
      { id: "yes", label: "Yes", probability: 42 },
      { id: "no", label: "No", probability: 58 },
    ],
    image: marketAi,
    trend: "up",
    description: "A market on whether a major AI research company announces a consumer-ready humanoid robot during 2026.",
    source: "Official company announcements",
    sourceUrl: "https://www.reuters.com/technology/",
    resolutionCriteria: "Resolves Yes after a public product announcement from a recognized AI lab; prototypes alone do not qualify.",
  },
  {
    id: "cricket-final",
    title: "Will the final be decided in the last five overs?",
    category: "Sports",
    closesAt: "6h 24m",
    volume: "610K TAC",
    participants: 4209,
    outcomes: [
      { id: "yes", label: "Yes", probability: 55 },
      { id: "no", label: "No", probability: 45 },
    ],
    image: marketCricket,
    trend: "flat",
    description: "Predict whether the match winner will be decided during the final five overs of the second innings.",
    source: "Official match scorecard",
    sourceUrl: "https://www.espncricinfo.com/",
    resolutionCriteria: "Resolves from the official completed match scorecard. Abandoned matches are cancelled.",
  },
  {
    id: "eth-5k",
    title: "Will Ethereum trade above $5,000 this year?",
    category: "Crypto",
    closesAt: "24d",
    volume: "1.1M TAC",
    participants: 8952,
    outcomes: [
      { id: "yes", label: "Yes", probability: 38 },
      { id: "no", label: "No", probability: 62 },
    ],
    trend: "down",
    description: "Tracks whether Ethereum trades above $5,000 on a major USD spot exchange before year end.",
    source: "CoinGecko",
    sourceUrl: "https://www.coingecko.com/en/coins/ethereum",
    resolutionCriteria: "Resolves Yes if the reported Ethereum USD spot price exceeds $5,000 before market close.",
  },
  {
    id: "rate-cut",
    title: "Will the next central bank decision cut rates?",
    category: "Business",
    closesAt: "4d 12h",
    volume: "955K TAC",
    participants: 7124,
    outcomes: [
      { id: "yes", label: "Yes", probability: 71 },
      { id: "no", label: "No", probability: 29 },
    ],
    trend: "up",
    description: "Predict whether the next announced central bank policy decision includes a reduction in its benchmark interest rate.",
    source: "Official central bank release",
    sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    resolutionCriteria: "Resolves from the official policy statement published after the next scheduled decision.",
  },
  {
    id: "global-tech-event",
    title: "Which category will lead the next global tech event?",
    category: "Technology",
    closesAt: "9d",
    volume: "384K TAC",
    participants: 2901,
    outcomes: [
      { id: "ai", label: "AI", probability: 49 },
      { id: "xr", label: "XR", probability: 27 },
      { id: "robotics", label: "Robotics", probability: 24 },
    ],
    trend: "flat",
    description: "Predict which technology category receives the greatest share of major product announcements at the next global event.",
    source: "Official event announcements",
    sourceUrl: "https://www.reuters.com/technology/",
    resolutionCriteria: "Resolves using the event organizer's official program and product announcement archive.",
  },
];

export const categories = [
  "All",
  "Crypto",
  "Sports",
  "News",
  "Technology",
  "Business",
  "Culture",
  "Other",
] as const;